## Using NumPy


In [4]:
import numpy as np



## Creating NumPy Arrays

### From a Python List



In [5]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [6]:
np.array(my_list)

array([1, 2, 3])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods



### arange



In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones



In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace


In [16]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye



In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 



### rand


In [19]:
np.random.rand(2)

array([0.09405885, 0.81083526])

In [20]:
np.random.rand(5,5)

array([[0.42078537, 0.92079994, 0.59520539, 0.43597415, 0.85439482],
       [0.66073239, 0.19785697, 0.52149672, 0.56095934, 0.75138776],
       [0.90525462, 0.74382979, 0.40080815, 0.71302841, 0.62772978],
       [0.92776347, 0.86308912, 0.59001722, 0.41216932, 0.85503079],
       [0.79850912, 0.19827138, 0.38807236, 0.38715643, 0.57231272]])

### randn



In [21]:
np.random.randn(2)

array([0.76645838, 1.20442236])

In [22]:
np.random.randn(5,5)

array([[ 1.53844686,  1.56409852,  0.01901635, -0.26405741, -0.02846929],
       [-0.21975917, -0.28577338, -0.99037532,  0.79444876, -1.85867543],
       [ 1.34248988, -0.01241476, -0.83112394,  0.02184978, -0.71266593],
       [ 0.96668879, -0.10151428,  1.01509083, -0.53279122,  0.40256247],
       [ 1.21639918,  0.64405298, -0.55621116,  0.82819608,  0.06077622]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [23]:
np.random.randint(1,100)

80

In [24]:
np.random.randint(1,100,10)

array([96, 81, 21, 70, 14, 14,  1, 85, 29, 42])

## Array Attributes and Methods



In [28]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr

array([23, 20, 45,  1, 15,  9,  4, 30, 21, 15])

## Reshape


In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin


In [32]:
ranarr

array([23, 20, 45,  1, 15,  9,  4, 30, 21, 15])

In [33]:
ranarr.max()

45

In [34]:
ranarr.argmax()

2

In [35]:
ranarr.min()

1

In [36]:
ranarr.argmin()

3

## Shape



In [37]:
# Vector
arr.shape

(25,)

In [38]:

arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [39]:
arr.reshape(1,25).shape

(1, 25)

In [40]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [41]:
arr.reshape(25,1).shape

(25, 1)

### dtype


In [42]:
arr.dtype

dtype('int32')